### ISSUE TITLE
i am trying to connect tcp communication with my computer. 

### ISSUE THREAD

**Issue by himhan34** [waterlinked/dvl-python#1]
hello, i am a student in korea. and i am working with your company's device called DVL-a50. 
i want to connect DVL-a50 with my laptop-computer. i am trying to connect through TCP communication. 

frist i connect DVL-A50 with len cable like this. 
![image](https://user-images.githubusercontent.com/46841767/159859099-770945ee-3733-4811-bc04-535b53e7f550.png)

secondly i connected with dc power supply to supply 20v to DVL-a50

thirdly i downloaded the file of dvl-python which is in github 

fourth. i implemented the venv 

finally i executed these two command below. 
1.python plot_dead_reckoning_positions.py "dvl_data.csv"
2.python dvl_tcp_parser.py dead_reckoning -c "dvl_data.csv"

and the result was this
![image](https://user-images.githubusercontent.com/46841767/159859893-22c918a1-5221-42ec-b89b-f843b66e3579.png)

i want to know how to use it. 
thank you for reading.

**Comment by himhan34** [comment]
Do i have to write my ip in here? 
![image](https://user-images.githubusercontent.com/46841767/159862306-0a48f75b-655f-4014-9d45-310ece2cfcb8.png)

**Comment by water-linked-richard-williamson** [comment]
Hi! Thank you for trying this out, and for the good documentation of your problem! Yes, this looks like a networking issue; one can pass the IP address of the DVL into the script via the -i argument, e.g. as follows.

python dvl_tcp_parser.py dead_reckoning -c "dvl_data.csv" -i 10.11.12.13

However, 192.168.2.95 is used by default, and the DVL should be accessible at this IP address, so it might well be that the networking issues are more subtle. 

Great that you have also contacted us on support, I'll continue the discussion there to see if we can get to the bottom of this :-).
